swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for fetching transactions of the month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions fetched successully
          schema:
            $ref: '#/definitions/TransactionAllResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transaction/{id}:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction API
      description: API for fetching specific transaction details
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          type: string
          description: Attach transaction ID to URL
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions details fetched successully
          schema:
            $ref: '#/definitions/TransactionAllResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  put:
    security:
      - Bearer: []
    tags:
      -Transaction Module
    summary: Transaction API
    description: API for updating a specific transaction detail
    parameters:
      -in: header
       type: string
       name: Authorization
       description: Attach Bearer JWT token
       required: true
      -in: path
       name: id
       type: string
       description: Attach transaction ID to URL
       required: true
      -in: body
        name: body
        description: Update user profile attributes
        required: true
        schema:
          $ref: '#/definitions/Transactions'
    produces:
        - application/json
      responses:
        '200':
          description: Transactions details updated successully
          schema:
            $ref: '#/definitions/TransactionAllResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  delete:
    security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for deleting a specific transaction detail
      parameters:
        -in: header
        type: string
        name: Authorization
        description: Attach Bearer JWT token
        required: true
        -in: path
        name: id
        type: string
        description: Attach transaction ID to URL
        required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions details deleted successully
          schema:
            $ref: '#/definitions/TransactionAllResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    properties:
      type:
        type: string
        description: transaction type
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: user notes
  TransactionAllResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: unique id
            date:
              type: string
              description: transaction date
            description:
              type: string
              description: transaction description
            amount:
              type: number
              description: transaction amount
            balance:
              type: number
              description: balance amount
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          items:
            type: string
          category:
            type: string
          notes:
            type: string
  TransactionUpdateResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: unique id
            date:
              type: string
              description: transaction date
            description:
              type: string
              description: transaction description
            amount:
              type: number
              description: transaction amount
            balance:
              type: number
              description: balance amount